apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - configmap.yaml
  - secret.yaml
  - ingress.yaml
  - hpa.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: docker.io/example/oauth2-server
    newTag: latest

labels:
  - pairs:
      app.kubernetes.io/name: oauth2-server
      app.kubernetes.io/instance: test
    includeSelectors: true
    includeTemplates: true
