[package]
name = "oauth2-ports"
version = "0.6.2"
edition = "2021"
rust-version.workspace = true
license = "MIT OR Apache-2.0"
description = "Ports (traits) for integrating rust-oauth2-server core with custom adapters (storage, etc.)"
repository = "https://github.com/ianlintner/rust_oauth2_server"

[dependencies]
async-trait = "0.1"
chrono = { version = "0.4", features = ["serde"] }
oauth2-core = { path = "../oauth2-core", version = "0.6.2" }
