apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-server
spec:
  replicas: 1
  template:
    spec: # nosemgrep: yaml.kubernetes.security.run-as-non-root
      # This is a Kustomize patch file; the base deployment already defines runAsNonRoot: true.
      containers:
        - name: oauth2-server
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
